# array of local keys to add
local_ssh_keys: []
git_user_password: WFltGBxB/v4Fs

repos: []
#   - name: ansible
#     remote: git@github.com:icpcsysops/ansible
#     deploy_key: ansible-deploykey

#   - name: wf49baku
#     remote: git@github.com:icpcsysops/wf49baku
#     deploy_key: wf49baku-deploykey
